// Code generated by entc, DO NOT EDIT.

package answer

import (
	"time"
)

const (
	// Label holds the string label denoting the answer type in the database.
	Label = "answer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// FieldNumOfVotes holds the string denoting the numofvotes field in the database.
	FieldNumOfVotes = "num_of_votes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeQuestionID holds the string denoting the question_id edge name in mutations.
	EdgeQuestionID = "question_id"
	// Table holds the table name of the answer in the database.
	Table = "answers"
	// QuestionIDTable is the table that holds the question_id relation/edge. The primary key declared below.
	QuestionIDTable = "question_answer"
	// QuestionIDInverseTable is the table name for the Question entity.
	// It exists in this package in order to avoid circular dependency with the "question" package.
	QuestionIDInverseTable = "questions"
)

// Columns holds all SQL columns for answer fields.
var Columns = []string{
	FieldID,
	FieldBody,
	FieldNumOfVotes,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// QuestionIDPrimaryKey and QuestionIDColumn2 are the table columns denoting the
	// primary key for the question_id relation (M2M).
	QuestionIDPrimaryKey = []string{"question_id", "answer_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultNumOfVotes holds the default value on creation for the "numOfVotes" field.
	DefaultNumOfVotes int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)
